#!/bin/bash
# Project Thea — build a double-clickable launcher for a game in a CrossOver
# bottle, or for a DOS game under DOSBox-X.
#
#   make-launcher.sh bottle  "FTL"      "/Volumes/SisuGames/Games/ftl/FTLGame.exe"
#   make-launcher.sh dosbox  "Populous" "/Volumes/SisuGames/Games/populous2/app" POPULOUS.EXE
#
# The .app lands in ~/Applications. Drag it to the Dock like any other app.
#
# The real command lives in a shell script inside the bundle rather than being
# embedded in the AppleScript. That keeps paths with spaces out of AppleScript
# string literals (where a backslash escape is a syntax error, not a space), and
# it is the only sane place to put `nohup`: an applet's `do shell script ... &`
# child dies when the applet quits, which silently breaks the launcher.

set -uo pipefail

KIND="${1:-}"; NAME="${2:-}"; TARGET="${3:-}"; DOS_EXE="${4:-}"
CX_BOTTLE="${CX_BOTTLE:-SisuGames}"
OUT_DIR="${OUT_DIR:-$HOME/Applications}"
CXSTART="/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/cxstart"

usage() {
    cat >&2 <<USAGE
usage: $0 bottle <Name> <path/to/Game.exe>
       $0 dosbox <Name> <path/to/dos/dir> <PROGRAM.EXE>
env:   CX_BOTTLE (default SisuGames)   OUT_DIR (default ~/Applications)
USAGE
    exit 2
}

[ -n "$KIND" ] && [ -n "$NAME" ] && [ -n "$TARGET" ] || usage

q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

case "$KIND" in
    bottle)
        [ -x "$CXSTART" ] || { echo "CrossOver not found at $CXSTART" >&2; exit 1; }
        RUN="$(q "$CXSTART") --bottle $(q "$CX_BOTTLE") -- $(q "$TARGET")"
        ;;
    dosbox)
        [ -n "$DOS_EXE" ] || usage
        DBX="$(command -v dosbox-x)" || { echo "dosbox-x not on PATH" >&2; exit 1; }
        # -nopromptfolder belt-and-braces: the user config sets noprompt too, but
        # a fresh config would otherwise hang on an invisible folder panel.
        RUN="$(q "$DBX") -nopromptfolder -c $(q "mount c $TARGET") -c 'c:' -c $(q "$DOS_EXE")"
        ;;
    *) usage ;;
esac

APP="$OUT_DIR/$NAME.app"
mkdir -p "$OUT_DIR"
rm -rf "$APP"

VOLUME="$(printf '%s' "$TARGET" | awk -F/ '/^\/Volumes\//{print "/Volumes/" $3}')"

TMP="$(mktemp -d)"
cat > "$TMP/launcher.applescript" <<'APPLESCRIPT'
on run
	set me_ to POSIX path of (path to me)
	do shell script quoted form of (me_ & "Contents/Resources/launch.sh")
end run
APPLESCRIPT

osacompile -o "$APP" "$TMP/launcher.applescript" || { echo "osacompile failed" >&2; rm -rf "$TMP"; exit 1; }
rm -rf "$TMP"

cat > "$APP/Contents/Resources/launch.sh" <<LAUNCH
#!/bin/bash
# generated by make-launcher.sh — edit the generator, not this file
# arguments passed to osascript as argv, so no quoting to get wrong
alert() {
    /usr/bin/osascript -e 'on run argv
	display alert (item 1 of argv) message (item 2 of argv) as critical
end run' "\$1" "\$2" >/dev/null 2>&1
}
VOLUME=$(q "$VOLUME")
TARGET=$(q "$TARGET")
if [ -n "\$VOLUME" ] && [ ! -d "\$VOLUME" ]; then
    alert "The games drive isn't connected" "$NAME lives on \$VOLUME. Plug the drive in and try again."
    exit 1
fi
if [ ! -e "\$TARGET" ]; then
    alert "$NAME isn't installed yet" "Nothing found at \$TARGET"
    exit 1
fi
# nohup + full detach: without it the game dies the moment the applet quits
nohup $RUN >/dev/null 2>&1 &
disown 2>/dev/null
exit 0
LAUNCH
chmod +x "$APP/Contents/Resources/launch.sh"

# Give it its own icon if we can pull one out of the Windows executable.
if [ "$KIND" = "bottle" ] && command -v wrestool >/dev/null 2>&1 && command -v icotool >/dev/null 2>&1; then
    ID="$(mktemp -d)"
    if wrestool -x -t 14 "$TARGET" -o "$ID" >/dev/null 2>&1 \
       && icotool -x -o "$ID" "$ID"/*.ico >/dev/null 2>&1; then
        BIG="$(ls -S "$ID"/*.png 2>/dev/null | head -1)"
        if [ -n "$BIG" ]; then
            ICONSET="$ID/icon.iconset"; mkdir -p "$ICONSET"
            for sz in 16 32 128 256 512; do
                sips -z $sz $sz "$BIG" --out "$ICONSET/icon_${sz}x${sz}.png" >/dev/null 2>&1
            done
            iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/applet.icns" 2>/dev/null \
                && echo "  icon extracted from $(basename "$TARGET")"
        fi
    fi
    rm -rf "$ID"
fi

touch "$APP"
echo "built: $APP"
